version: "3.8"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bodtrack
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - 'mariadbdata:/var/lib/mysql'
  pma:
    image: phpmyadmin
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
  web:
    build:
      dockerfile: ./app/Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    develop:
      watch: 
        - path: ./
          action: sync
          target: /var/www/html
          ignore:
            - .git
volumes:
  mariadbdata: